message("================================================================================================================")
message("=                                                                                                              =")
message("=   Not support this device now, please update the arm_gcc_compile_config or contact the maintainer for help   =")
message("=                                                                                                              =")
message("================================================================================================================")
